### ISSUE TITLE
Automate the configuration of API gateway dev endpoint

### ISSUE THREAD

**Issue by dashinay** [ActoKids/devops#29]

**Comment by LyndonP** [comment]
## AUTOMATION TASK ##
- Create CNAME in Route53
- Configure API GW to use the CNAME + SSL certificate
- Configure the API Gateway to point to Lambda 

Estimated Time: 6 Hours

**Comment by LyndonP** [comment]
Sprint 4 Tasks
Automate the configuration of API gateway dev endpoint
Task Description:
•	Create CNAME in Route53                                                – (TERRAFORM)
•	Configure API GW to use the CNAME + SSL certificate – (TERRAFORM)
•	Configure the API Gateway to point to Lambda                – (TERRAFORM)
SOURCES:
-	[](https://andydote.co.uk/2017/03/17/terraform-aws-lambda-api-gateway/)
-	[](https://dev.to/frosnerd/deploying-an-http-api-on-aws-using-lambda-and-api-gateway-g61)
-	[](https://jarombek.com/blog/sep-7-2018-aws-lambda-api-gateway)
-	[](https://medium.com/onfido-tech/aws-api-gateway-with-terraform-7a2bebe8b68f)

To complete this task, I used the references above which talks about instantiating an API Gateway and binding both certificates and Lambda functions to it. The Lambda function itself uses the Dev function created by @ZakBrinlee. PLEASE NOTE: The Lambda function files need to exist in the SAME DIRECTORY as the .tf file.

The same can be done with POST, or, they can all be combined into one file.

**Estimated Hours:**
8 Hours
**Actual Hours:**
10 Hours
**GitHub Code:** [](https://github.com/ActoKids/devops/blob/LyndonP-apigw-dev/scripts/apigw%20dev/Sprint4_DEV.tf)
**PR:** [](https://github.com/ActoKids/devops/pull/38)
**SSL Enabled Dev URL:** [](https://api-dev.2edusite.com/)

**Comment by LyndonP** [comment]
**## Sprint 4 Tasks**
Automate the configuration of API gateway dev endpoint
**Task Description:**
•	Create CNAME in Route53                                             – (TERRAFORM)
•	Configure API GW to use the CNAME + SSL certificate – (TERRAFORM)
•	Configure the API Gateway to point to Lambda            – (TERRAFORM)
**#SOURCES:**	
-   [Link 1](https://andydote.co.uk/2017/03/17/terraform-aws-lambda-api-gateway/)
-   [Link 2](https://dev.to/frosnerd/deploying-an-http-api-on-aws-using-lambda-and-api-gateway-g61)
-   [Link 3](https://jarombek.com/blog/sep-7-2018-aws-lambda-api-gateway)
-   [Link 4](https://medium.com/onfido-tech/aws-api-gateway-with-terraform-7a2bebe8b68f)

**### To complete this task, I used the references above which talks about instantiating an API 
Gateway and binding both certificates and Lambda functions to it. The Lambda 
function itself uses the Dev function created by @ZakBrinlee.**

PLEASE NOTE: The Lambda function files need to exist in the SAME DIRECTORY as the .tf file.
The same can be done with POST, or, they can all be combined into one file.

**Estimated Hours:**
8 Hours
**Actual Hours:**
10 Hours

**[Pull Request](https://github.com/ActoKids/devops/pull/38)
[GitHub Code](https://github.com/ActoKids/devops/blob/LyndonP-apigw-dev/scripts/apigw%20dev)
[Wiki](https://github.com/ActoKids/devops/wiki/How-to-create-a-CNAME,-API-Gateway-and-Lambda-Function-in-AWS:-Bind-SSL-Certificate-to-API-Gateway)
[Issue](https://github.com/ActoKids/devops/issues/29)**


**Installing**

**1. Clone this repo (git clone)
2. Ensure AWS Creds are configured (aws configure)
3. Initialize Terraform (terraform init)
4. Verify plan (terraform plan)
5. Apply plan to your AWS account (aws apply)** 

**Testing:** 
After the command "terraform apply" check your AWS console for the following:
  - A new CNAME record in Route53
  - A newly configured API Gateway Using the CNAME + SSL certificate
  - And configured is the API Gateway pointing at Lambda funtion getEventById.js (lambda.zip)

![s4_script](https://user-images.githubusercontent.com/34604046/53706148-b4173f80-3ddd-11e9-8a2b-dfd1843bada6.gif)

**Comment by LyndonP** [comment]
**Bugs worked on this Sprint:**
[#79](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/79)

[#34](https://github.com/ActoKids/devops/issues/34)

[#85](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/85)

[#77](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/77)

**Comment by amy61789** [comment]
Reviewed Lyndon's PR and approved - notes are included in the [PR link](https://github.com/ActoKids/devops/pull/38)
